### ISSUE TITLE
Tracking items that need to be reflected when Klaytn changes

### ISSUE THREAD

**Issue by jimni1222** [klaytn/rosetta-klaytn#33]
There are several features that need to be changed in Klaytn. 
rosetta-klaytn is implemented based on the current Klaytn source code, and for the items below, if it is changed in Klaytn, it is necessary to apply in rosetta-klaytn alo.

- [x] https://github.com/klaytn/rosetta-klaytn/issues/49
- [x] https://github.com/klaytn/rosetta-klaytn/issues/15
- [x] https://github.com/klaytn/rosetta-klaytn/issues/50
